import { IMG } from "./content";
import type { Lang } from "./lang";

// ---- Mission / Statutes ---------------------------------------------------
// On the live site the statutes body is English across all languages, so we
// mirror that (single English source rendered on every locale).

export const MISSION_TITLE = "Statutes of the DeNode Foundation";

export const MISSION_SECTIONS: { heading: string; paras: string[] }[] = [
  {
    heading: "Purpose of the foundation (from the statutes)",
    paras: [
      "The private foundation is established for the pursuit of the following disinterested purpose.",
      "The purpose of the private foundation is to acquire, preserve, manage, make accessible, exhibit both publicly and privately, protect, safeguard, and expand art and artworks.",
      "In this context, the private foundation proceeds to inventory, describe, and archive the artworks in the broadest sense.",
      "Furthermore, the private foundation is allowed to improve its collection through sales, purchases, or exchanges with works held by other collectors, artists, or auction houses.",
    ],
  },
  {
    heading: "Supporting activities",
    paras: [
      "To support these activities, the private foundation can oversee the organization or provide support for all artistic achievements and cultural developments, and for organizing art galleries and art exhibitions, both at its own location and elsewhere.",
      "It can publish or distribute promotional material, in print, digitally, or in any other way, or collaborate on or provide support for such.",
    ],
  },
  {
    heading: "Concrete activities",
    paras: [
      "In particular, the private foundation, with a view to realizing this altruistic goal, may carry out the following activities both domestically and internationally:",
      "• The management and expansion of an art collection",
      "• The exhibition of the art collection",
      "• The acquisition of funds and resources necessary for financing the aforementioned purpose",
      "• Financing activities and projects to make the art collection better known to the general public and to inspire young artists",
      "• Facilitating projects with and for artists",
    ],
  },
  {
    heading: "Benefaction",
    paras: [
      "The Board of Directors shall exercise discretionary judgment regarding any potential distributions. Potential beneficiaries shall have no right of claim.",
      "The representation of these interests includes the support and funding of scientific, material, commercial, educational, intellectual, artistic, and other projects, without these individuals having a claim to it and without any distributions being made in cash.",
    ],
  },
  {
    heading: "Use of resources",
    paras: [
      "The private foundation pursues its altruistic goal simultaneously and may use the annual return on the foundation's assets for this purpose.",
      "The private foundation can increase its operating resources by transferring or lending artworks owned by the private foundation for a consideration at a market-conform price, but only to the extent necessary and with a view to preserving the continuity of the operation of the private foundation. The Board decides on this at its discretion with unanimity.",
      "The term 'annual return' shall be understood to mean: the income generated by the assets during that year, increased by realized capital gains on any asset component and unrealized capital gains on capitalization instruments, and decreased by realized capital losses on any asset component and unrealized capital losses on capitalization instruments.",
    ],
  },
  {
    heading: "Liquidation",
    paras: [
      "In the event of liquidation of the private foundation, all movable property, particularly all artworks and the art archive, will be transferred to reputable museums, chosen by the Board, in accordance with the altruistic goal.",
    ],
  },
  {
    heading: "Management of the assets",
    paras: [
      "The private foundation manages its assets like a good householder, with attention to preservation and valorization. It may carry out the following transactions, among others:",
      "• Movable and/or immovable transactions, such as entering into contracts.",
      "• Making investments, directly or indirectly (through the establishment of companies, investment companies, life insurance, etc.).",
      "• Invest in movable property and portfolio values, including securities and works of art.",
      "• Leasing, purchasing and selling, and establishing, constructing, renovating, or demolishing real estate.",
      "• Establish, purchase, or grant business rights, in Belgium or abroad.",
      "• Enter into loans and/or provide securities.",
      "• Assume costs and burdens to relieve the persons or institutions mentioned in the purpose.",
      "• Collaborate with, participate in, or take interests in enterprises of all kinds.",
      "• Transfer assets to other Belgian or foreign foundations or similar legal entities with a corresponding objective.",
      "• Exercise mandates (paid or unpaid) in legal entities.",
    ],
  },
  {
    heading: "Other provisions",
    paras: [
      "The private foundation may furthermore perform all acts that directly or indirectly relate to its purpose. It may provide cooperation and participate in any activity that aligns with its purpose.",
      "The private foundation may not provide any material benefit to the founder(s), directors, or any other person, except if this is part of achieving the altruistic purpose.",
    ],
  },
];

// Authentic NL/FR of the statutes do not exist on denode.be (the page is English
// there in every language), so these are AI translations shown with a notice.
export const MISSION_LOCALES: Partial<
  Record<Lang, { title: string; sections: { heading: string; paras: string[] }[] }>
> = {
  nl: {
    title: "Statuten van de Stichting DeNode",
    sections: [
      {
        heading: "Doel van de stichting (uit de statuten)",
        paras: [
          "De private stichting is opgericht voor de verwezenlijking van het volgende belangeloze doel.",
          "Het doel van de private stichting is het verwerven, bewaren, beheren, toegankelijk maken, zowel publiek als privaat tentoonstellen, beschermen, veiligstellen en uitbreiden van kunst en kunstwerken.",
          "In dit kader gaat de private stichting over tot het inventariseren, beschrijven en archiveren van de kunstwerken in de ruimste zin.",
          "Voorts mag de private stichting haar collectie verbeteren via verkoop, aankoop of ruil met werken die worden aangehouden door andere verzamelaars, kunstenaars of veilinghuizen.",
        ],
      },
      {
        heading: "Ondersteunende activiteiten",
        paras: [
          "Ter ondersteuning van deze activiteiten kan de private stichting instaan voor de organisatie of ondersteuning bieden aan alle artistieke verwezenlijkingen en culturele ontwikkelingen, en voor het inrichten van kunstgalerijen en kunsttentoonstellingen, zowel op haar eigen locatie als elders.",
          "Zij kan promotiemateriaal publiceren of verspreiden, in druk, digitaal of op elke andere wijze, of daaraan meewerken of daarvoor ondersteuning bieden.",
        ],
      },
      {
        heading: "Concrete activiteiten",
        paras: [
          "In het bijzonder mag de private stichting, met het oog op de verwezenlijking van dit belangeloze doel, de volgende activiteiten uitvoeren, zowel in binnen- als buitenland:",
          "• Het beheer en de uitbreiding van een kunstcollectie",
          "• De tentoonstelling van de kunstcollectie",
          "• De verwerving van middelen en fondsen nodig voor de financiering van voormeld doel",
          "• Het financieren van activiteiten en projecten om de kunstcollectie beter bekend te maken bij het brede publiek en om jonge kunstenaars te inspireren",
          "• Het faciliteren van projecten met en voor kunstenaars",
        ],
      },
      {
        heading: "Weldadigheid",
        paras: [
          "De raad van bestuur oefent een discretionaire beoordeling uit met betrekking tot mogelijke uitkeringen. Mogelijke begunstigden hebben geen vorderingsrecht.",
          "De behartiging van deze belangen omvat de ondersteuning en financiering van wetenschappelijke, materiële, commerciële, educatieve, intellectuele, artistieke en andere projecten, zonder dat deze personen daarop aanspraak kunnen maken en zonder dat er uitkeringen in geld gebeuren.",
        ],
      },
      {
        heading: "Aanwending van de middelen",
        paras: [
          "De private stichting streeft haar belangeloze doel gelijktijdig na en mag daartoe het jaarlijkse rendement van het vermogen van de stichting aanwenden.",
          "De private stichting kan haar werkingsmiddelen verhogen door kunstwerken in eigendom van de private stichting tegen vergoeding aan een marktconforme prijs over te dragen of uit te lenen, maar enkel voor zover noodzakelijk en met het oog op het behoud van de continuïteit van de werking van de private stichting. De raad beslist hierover naar eigen goeddunken en met eenparigheid.",
          "Onder 'jaarlijks rendement' wordt verstaan: de inkomsten die het vermogen tijdens dat jaar genereert, verhoogd met gerealiseerde meerwaarden op enig vermogensbestanddeel en niet-gerealiseerde meerwaarden op kapitalisatie-instrumenten, en verminderd met gerealiseerde minderwaarden op enig vermogensbestanddeel en niet-gerealiseerde minderwaarden op kapitalisatie-instrumenten.",
        ],
      },
      {
        heading: "Vereffening",
        paras: [
          "In geval van vereffening van de private stichting worden alle roerende goederen, in het bijzonder alle kunstwerken en het kunstarchief, overgedragen aan gerenommeerde musea, gekozen door de raad, in overeenstemming met het belangeloze doel.",
        ],
      },
      {
        heading: "Beheer van het vermogen",
        paras: [
          "De private stichting beheert haar vermogen als een goede huisvader, met aandacht voor behoud en valorisatie. Zij mag onder meer de volgende verrichtingen uitvoeren:",
          "• Roerende en/of onroerende verrichtingen, zoals het sluiten van contracten.",
          "• Het doen van investeringen, rechtstreeks of onrechtstreeks (via de oprichting van vennootschappen, investeringsvennootschappen, levensverzekeringen, enz.).",
          "• Investeren in roerende goederen en portefeuillewaarden, waaronder effecten en kunstwerken.",
          "• Het leasen, aankopen en verkopen, en het oprichten, bouwen, renoveren of afbreken van onroerend goed.",
          "• Het vestigen, aankopen of verlenen van zakelijke rechten, in België of in het buitenland.",
          "• Leningen aangaan en/of zekerheden verstrekken.",
          "• Kosten en lasten op zich nemen om de in het doel vermelde personen of instellingen te ontlasten.",
          "• Samenwerken met, deelnemen in of belangen nemen in ondernemingen van alle aard.",
          "• Vermogen overdragen aan andere Belgische of buitenlandse stichtingen of soortgelijke rechtspersonen met een overeenstemmend doel.",
          "• Mandaten uitoefenen (bezoldigd of onbezoldigd) in rechtspersonen.",
        ],
      },
      {
        heading: "Overige bepalingen",
        paras: [
          "De private stichting mag voorts alle handelingen stellen die rechtstreeks of onrechtstreeks verband houden met haar doel. Zij mag medewerking verlenen aan en deelnemen aan elke activiteit die met haar doel overeenstemt.",
          "De private stichting mag geen enkel materieel voordeel verschaffen aan de stichter(s), bestuurders of enige andere persoon, tenzij dit deel uitmaakt van de verwezenlijking van het belangeloze doel.",
        ],
      },
    ],
  },
  fr: {
    title: "Statuts de la Fondation DeNode",
    sections: [
      {
        heading: "But de la fondation (extrait des statuts)",
        paras: [
          "La fondation privée est constituée en vue de la réalisation du but désintéressé suivant.",
          "Le but de la fondation privée est d'acquérir, de conserver, de gérer, de rendre accessibles, d'exposer tant publiquement que de manière privée, de protéger, de sauvegarder et d'enrichir l'art et les œuvres d'art.",
          "Dans ce cadre, la fondation privée procède à l'inventaire, à la description et à l'archivage des œuvres d'art au sens le plus large.",
          "En outre, la fondation privée peut améliorer sa collection par la vente, l'achat ou l'échange d'œuvres détenues par d'autres collectionneurs, artistes ou maisons de vente aux enchères.",
        ],
      },
      {
        heading: "Activités de soutien",
        paras: [
          "Pour soutenir ces activités, la fondation privée peut assurer l'organisation ou apporter son soutien à toutes les réalisations artistiques et développements culturels, ainsi qu'à l'organisation de galeries d'art et d'expositions, tant sur son propre site qu'ailleurs.",
          "Elle peut publier ou diffuser du matériel promotionnel, sous forme imprimée, numérique ou de toute autre manière, ou y collaborer ou y apporter son soutien.",
        ],
      },
      {
        heading: "Activités concrètes",
        paras: [
          "En particulier, en vue de réaliser ce but désintéressé, la fondation privée peut mener les activités suivantes, tant au niveau national qu'international :",
          "• La gestion et l'enrichissement d'une collection d'art",
          "• L'exposition de la collection d'art",
          "• L'acquisition des moyens et ressources nécessaires au financement du but précité",
          "• Le financement d'activités et de projets visant à mieux faire connaître la collection d'art auprès du grand public et à inspirer les jeunes artistes",
          "• La facilitation de projets avec et pour les artistes",
        ],
      },
      {
        heading: "Bienfaisance",
        paras: [
          "Le conseil d'administration exerce un pouvoir d'appréciation discrétionnaire quant aux éventuelles distributions. Les bénéficiaires potentiels ne disposent d'aucun droit de créance.",
          "La défense de ces intérêts comprend le soutien et le financement de projets scientifiques, matériels, commerciaux, éducatifs, intellectuels, artistiques et autres, sans que ces personnes puissent y prétendre et sans qu'aucune distribution ne soit faite en espèces.",
        ],
      },
      {
        heading: "Emploi des ressources",
        paras: [
          "La fondation privée poursuit son but désintéressé de manière simultanée et peut à cette fin employer le rendement annuel du patrimoine de la fondation.",
          "La fondation privée peut augmenter ses moyens de fonctionnement en cédant ou en prêtant, contre rémunération à un prix conforme au marché, des œuvres d'art dont elle est propriétaire, mais uniquement dans la mesure nécessaire et en vue de préserver la continuité de son fonctionnement. Le conseil en décide à sa discrétion et à l'unanimité.",
          "Par « rendement annuel », on entend : les revenus générés par le patrimoine au cours de cette année, augmentés des plus-values réalisées sur tout élément du patrimoine et des plus-values non réalisées sur les instruments de capitalisation, et diminués des moins-values réalisées sur tout élément du patrimoine et des moins-values non réalisées sur les instruments de capitalisation.",
        ],
      },
      {
        heading: "Liquidation",
        paras: [
          "En cas de liquidation de la fondation privée, tous les biens mobiliers, en particulier toutes les œuvres d'art et les archives artistiques, seront transférés à des musées réputés, choisis par le conseil, conformément au but désintéressé.",
        ],
      },
      {
        heading: "Gestion du patrimoine",
        paras: [
          "La fondation privée gère son patrimoine en bon père de famille, avec le souci de sa conservation et de sa valorisation. Elle peut notamment effectuer les opérations suivantes :",
          "• Des opérations mobilières et/ou immobilières, telles que la conclusion de contrats.",
          "• Réaliser des investissements, directement ou indirectement (par la constitution de sociétés, de sociétés d'investissement, d'assurances-vie, etc.).",
          "• Investir dans des biens mobiliers et des valeurs de portefeuille, y compris des titres et des œuvres d'art.",
          "• Louer, acheter et vendre, ainsi qu'établir, construire, rénover ou démolir des biens immobiliers.",
          "• Constituer, acquérir ou accorder des droits réels, en Belgique ou à l'étranger.",
          "• Contracter des emprunts et/ou fournir des sûretés.",
          "• Assumer des frais et des charges pour décharger les personnes ou institutions mentionnées dans le but.",
          "• Collaborer avec, participer à ou prendre des intérêts dans des entreprises de toute nature.",
          "• Transférer des biens à d'autres fondations belges ou étrangères ou à des personnes morales similaires ayant un objet correspondant.",
          "• Exercer des mandats (rémunérés ou non) dans des personnes morales.",
        ],
      },
      {
        heading: "Autres dispositions",
        paras: [
          "La fondation privée peut en outre accomplir tous les actes se rapportant directement ou indirectement à son but. Elle peut apporter sa collaboration et participer à toute activité conforme à son but.",
          "La fondation privée ne peut procurer aucun avantage matériel au(x) fondateur(s), aux administrateurs ou à toute autre personne, sauf si cela s'inscrit dans la réalisation du but désintéressé.",
        ],
      },
    ],
  },
};

// Authentic Dutch statutes captured from denode.be (the statutes were originally
// written in Dutch). Rendered as-is on NL — no AI notice.
export const MISSION_NL: { title: string; sections: { heading: string; paras: string[] }[] } = {
  title: "Statuten Stichting DeNode",
  sections: [
    {
      heading: "Doel van de stichting (uit de statuten)",
      paras: [
        "De private stichting wordt opgericht ter verwezenlijking van het volgend belangeloos doel:",
        "Het doel van de private stichting bestaat uit het verwerven, het behouden, het beheren, het toegankelijk maken, het (laten) tentoonstellen zowel publiek als privé, het beschermen, het vrijwaren en het uitbreiden van kunst en kunstwerken.",
        "In dat verband gaat de private stichting over tot het inventariseren, het beschrijven en het archiveren van de kunstwerken in de meest ruime zin.",
        "Bovendien is het de private stichting toegelaten haar collectie te verbeteren door verkoop, inkoop of ruiling met werken in handen van andere verzamelaars, kunstenaars of veilinghuizen.",
      ],
    },
    {
      heading: "Ondersteunende activiteiten",
      paras: [
        "Om deze activiteiten te ondersteunen kan de private stichting de organisatie waarnemen of steun verlenen aan alle kunstzinnige prestaties en culturele ontwikkelingen, en aan het organiseren van kunstgalerijen en kunsttentoonstellingen, zowel op haar eigen locatie als elders.",
        "Zij kan publicaties of promotiemateriaal uitgeven, op papier, digitaal of op enige andere wijze, of eraan meewerken of steun verlenen.",
      ],
    },
    {
      heading: "Concrete activiteiten",
      paras: [
        "In het bijzonder kan de private stichting, met het oog op de realisatie van dit belangeloze doel, onder meer de volgende activiteiten verrichten in binnen- en buitenland:",
        "• Het beheer en de uitbouw van een kunstcollectie",
        "• Het tentoonstellen van de kunstcollectie",
        "• Het verwerven van fondsen en gelden nodig voor de financiering van voormeld doel",
        "• Het financieren van activiteiten en projecten om de kunstcollectie aan het grote publiek bekender te maken en om jonge kunstenaars te inspireren",
        "• Het faciliteren van projecten met en voor kunstenaars",
      ],
    },
    {
      heading: "Begunstiging",
      paras: [
        "Het Bestuursorgaan zal discretionair oordelen over een eventuele begunstiging. Mogelijke begunstigden hebben geen vorderingsrecht.",
        "Onder de behartiging van deze belangen wordt onder meer verstaan: de ondersteuning en financiering van wetenschappelijke, materiële, commerciële, educatieve, intellectuele, kunstzinnige en andere projecten, zonder dat deze personen daartoe een vorderingsrecht hebben en zonder dat er uitkeringen in speciën worden gedaan.",
      ],
    },
    {
      heading: "Aanwending van middelen",
      paras: [
        "De private stichting behartigt haar belangeloos doel gelijktijdig en mag hiervoor het jaarlijks rendement van het vermogen van de stichting aanwenden.",
        "De private stichting kan haar werkingsmiddelen vergroten door kunstwerken in het bezit van de private stichting ten bezwarende titel over te dragen of uit te lenen tegen een marktconforme prijs, doch enkel in zoverre als noodzakelijk en met het oog op de bewaring van de continuïteit van de werking van de private stichting. Het Bestuursorgaan beslist hierover discretionair met unanimiteit.",
        "Onder de notie \"jaarlijks rendement\" moet worden verstaan: de vruchten die het vermogen gedurende dat jaar heeft opgeleverd, te verhogen met de gerealiseerde meerwaarden op eender welk actiefbestanddeel en de niet gerealiseerde meerwaarden van de kapitalisatiestukken en te verminderen met de gerealiseerde minwaarden op eender welk actiefbestanddeel en de niet gerealiseerde minwaarden op kapitalisatiestukken.",
      ],
    },
    {
      heading: "Liquidatie",
      paras: [
        "Bij liquidatie van de private stichting worden alle roerende goederen, in het bijzonder alle kunstwerken en het kunstarchief, overgedragen aan gerenommeerde musea, gekozen door het Bestuursorgaan, in overeenstemming met het belangeloos doel.",
      ],
    },
    {
      heading: "Beheer van het vermogen",
      paras: [
        "De private stichting beheert haar vermogen als een goede huisvader, met aandacht voor instandhouding en valorisatie. Zij kan onder meer de volgende verrichtingen stellen:",
        "• Roerende en/of onroerende verrichtingen, zoals het sluiten van contracten.",
        "• Beleggingen verrichten, rechtstreeks of onrechtstreeks (via oprichting van vennootschappen, beleggingsvennootschappen, levensverzekeringen, enz.).",
        "• Investeren in roerende goederen en portefeuillewaarden, waaronder effecten en kunstvoorwerpen.",
        "• Verhuren, aan- en verkopen, oprichten, bouwen, verbouwen en afbreken van onroerende goederen.",
        "• Vestigen, aankopen of toestaan van zakelijke rechten, in België of daarbuiten.",
        "• Leningen aangaan en/of zekerheden verstrekken.",
        "• Kosten en lasten op zich nemen ter ontlasting van in het doel vernoemde personen of instellingen.",
        "• Verbintenissen uitvoeren ten laste van die personen of instellingen.",
        "• Samenwerken met, deelnemen in of belangen nemen in ondernemingen van allerlei aard.",
        "• Lijfrenteovereenkomsten aangaan met de in het derde doel gedefinieerde personen.",
        "• Vermogen overdragen aan andere Belgische of buitenlandse stichtingen of gelijkaardige rechtsfiguren met een overeenkomstige doelstelling.",
        "• Mandaten uitoefenen (bezoldigd of niet) in rechtspersonen.",
      ],
    },
    {
      heading: "Overige bepalingen",
      paras: [
        "De private stichting kan alle handelingen stellen die rechtstreeks of onrechtstreeks betrekking hebben op haar doel. Zij kan medewerking verlenen en deelnemen aan iedere activiteit die met haar doel overeenstemt.",
        "De private stichting mag geen stoffelijk voordeel verschaffen aan de stichter(s), bestuurders of enig ander persoon, behalve indien dit kadert in de verwezenlijking van het belangeloos doel.",
      ],
    },
  ],
};


// ---- Team -----------------------------------------------------------------

interface Member {
  name: string;
  role: string;
  bio: string;
  img: string;
}

interface TeamContent {
  aboutHeading: string;
  tagline: string;
  aboutParas: string[];
  teamHeading: string;
  teamSub: string;
  members: Member[];
  volunteersHeading: string;
  volunteersBody: string;
}

export const TEAM: Record<Lang, TeamContent> = {
  en: {
    aboutHeading: "About DeNode Foundation",
    tagline: "A platform for research, creation, and dialogue.",
    aboutParas: [
      "The DeNode Foundation is a non-profit organization based in Ghent dedicated to supporting contemporary art. We believe in artistic practices that look beyond the surface. Therefore, we focus on long-term projects and in-depth research, where the process is at least as important as the end result.",
      "Our foundation is a vibrant ecosystem where exhibitions, residencies, public programs, and editorial projects come together. Instead of limiting ourselves to one medium, we embrace interdisciplinary practices that engage in dialogue with the social, cultural, and philosophical issues of our time. In this way, we bridge the local Ghent scene and the international art field.",
    ],
    teamHeading: "Team",
    teamSub: "The core team of DeNode",
    members: [
      {
        name: "Paul De Cannière",
        role: "Founder & Strategic Vision",
        bio: "Driven by the desire to create a free space for collective reflection, Paul laid the foundation for DeNode. With a keen eye for technological innovation and a strong social commitment, he focuses on projects that transcend conventional formats and aim to generate sustainable impact.",
        img: IMG.paul,
      },
      {
        name: "Kristof Vander Cruyssen",
        role: "Curator & Artistic Development",
        bio: "As an artist and curator, Kristof brings deep insight into artistic ecosystems to the foundation. He oversees the artistic direction and guides the development of exhibitions and residencies. His expertise combines curatorial precision with pragmatic knowledge of production processes.",
        img: IMG.kristof,
      },
      {
        name: "Hanna Ouaziz",
        role: "Curatorial & International Programs",
        bio: "Hanna shapes the substantive narratives and international collaborations of DeNode. With a background in philosophy and anthropology, she weaves thematic research together with engaged art practices. She is the linchpin of our international network and responsible for the editorial projects that deepen our vision.",
        img: IMG.hanna,
      },
    ],
    volunteersHeading: "Volunteers and staff",
    volunteersBody:
      "The realization of our program would be impossible without the tireless dedication of our many staff and volunteers. We see them not just as support, but as co-creators. More information about their individual practices can be found on our Artists page, as they are each the creative engine of our organization.",
  },
  fr: {
    aboutHeading: "À propos de la Fondation DeNode",
    tagline: "Une plateforme pour la recherche, la création et le dialogue.",
    aboutParas: [
      "La DeNode Foundation est une organisation à but non lucratif basée à Gand, dédiée au soutien de l'art contemporain. Nous croyons en des pratiques artistiques qui vont au-delà de la surface. Par conséquent, nous nous concentrons sur des projets à long terme et des recherches approfondies, où le processus est au moins aussi important que le résultat final.",
      "Notre fondation est un écosystème dynamique où les expositions, les résidences, les programmes publics et les projets éditoriaux se rejoignent. Au lieu de nous limiter à un seul médium, nous embrassons des pratiques interdisciplinaires qui dialoguent avec les enjeux sociaux, culturels et philosophiques de notre époque. De cette manière, nous faisons le lien entre la scène locale de Gand et le domaine artistique international.",
    ],
    teamHeading: "Équipe",
    teamSub: "L'équipe principale de DeNode",
    members: [
      {
        name: "Paul De Cannière",
        role: "Fondateur & Vision Stratégique",
        bio: "Animé par le désir de créer un espace libre pour la réflexion collective, Paul a posé les bases de DeNode. Avec un œil attentif à l'innovation technologique et un fort engagement social, il se concentre sur des projets qui transcendent les formats conventionnels et visent à générer un impact durable.",
        img: IMG.paul,
      },
      {
        name: "Kristof Vander Cruyssen",
        role: "Directeur artistique & curateur",
        bio: "En tant que chercheur en art et artiste, Kristof apporte à la fondation une compréhension approfondie des écosystèmes artistiques. Il veille à la direction artistique et accompagne le développement des expositions et des résidences. Son expertise associe une précision curatoriale à une connaissance pragmatique des processus de production.",
        img: IMG.kristof,
      },
      {
        name: "Hanna Ouaziz",
        role: "Programmes de conservation et internationaux",
        bio: "Hanna façonne les récits substantiels et les collaborations internationales de DeNode. Avec un parcours en philosophie et en anthropologie, elle tisse la recherche thématique avec des pratiques artistiques engagées. Elle est le pivot de notre réseau international et responsable des projets éditoriaux qui approfondissent notre vision.",
        img: IMG.hanna,
      },
    ],
    volunteersHeading: "Bénévoles et personnel",
    volunteersBody:
      "La réalisation de notre programme serait impossible sans le dévouement inflexible de notre nombreux personnel et bénévoles. Nous les considérons non seulement comme un soutien, mais comme des co-créateurs. Plus d'informations sur leurs pratiques individuelles peuvent être trouvées sur notre page Artistes, car chacun d'eux est le moteur créatif de notre organisation.",
  },
  nl: {
    aboutHeading: "Over Stichting DeNode",
    tagline: "Een platform voor onderzoek, creatie en dialoog.",
    aboutParas: [
      "Stichting DeNode is een Gentse non-profitorganisatie die zich inzet voor de ondersteuning van hedendaagse kunst. Wij geloven in artistieke praktijken die verder kijken dan het oppervlak. Daarom richten wij ons op langdurige trajecten en diepgaand onderzoek, waarbij het proces minstens even belangrijk is als het eindresultaat.",
      "Onze stichting is een levendig ecosysteem waar tentoonstellingen, residenties, publieke programma's en redactionele projecten samenkomen. In plaats van ons te beperken tot één medium, omarmen we interdisciplinaire praktijken die de dialoog aangaan met sociale, culturele en filosofische vraagstukken van deze tijd. Zo slaan we een brug tussen de lokale Gentse scene en het internationale kunstenveld.",
    ],
    teamHeading: "Team",
    teamSub: "De vaste kern van DeNode",
    members: [
      {
        name: "Paul De Cannière",
        role: "Oprichter & Strategische Visie",
        bio: "Gedreven door de wens om een vrije ruimte te creëren voor collectieve reflectie, legde Paul de basis voor DeNode. Met een scherp oog voor technologische innovatie en een sterke sociale bewogenheid, richt hij zich op projecten die conventionele formats overstijgen en een duurzame impact willen genereren.",
        img: IMG.paul,
      },
      {
        name: "Kristof Vander Cruyssen",
        role: "Artistieke leider & curator",
        bio: "Als kunstwetenschapper en kunstenaar brengt Kristof een diepgaand inzicht in artistieke ecosystemen mee naar de stichting. Hij bewaakt de artistieke koers en begeleidt de ontwikkeling van tentoonstellingen en residenties. Zijn expertise koppelt curatoriële precisie aan een pragmatische kennis van productieprocessen.",
        img: IMG.kristof,
      },
      {
        name: "Hanna Ouaziz",
        role: "Curatoriële & Internationale Programma's",
        bio: "Hanna geeft vorm aan de inhoudelijke narratieven en internationale samenwerkingen van DeNode. Vanuit een achtergrond in de filosofie en antropologie weeft zij thematisch onderzoek samen met geëngageerde kunstpraktijken. Zij is de spil in ons internationale netwerk en verantwoordelijk voor de redactionele projecten die onze visie verdiepen.",
        img: IMG.hanna,
      },
    ],
    volunteersHeading: "Vrijwilligers en medewerkers",
    volunteersBody:
      "De realisatie van ons programma zou onmogelijk zijn zonder de tomeloze inzet van onze vele medewerkers en vrijwilligers. Wij beschouwen hen niet alleen als ondersteuning, maar als mede-makers. Meer informatie over hun individuele praktijken is te vinden op onze Kunstenaars-pagina, want zij zijn stuk voor stuk de creatieve motor van onze organisatie.",
  },
};

// ---- Cookie policy (concise notice — replace with official legal text) -----

interface CookieContent {
  title: string;
  body: string[];
}

export const COOKIE: Record<Lang, CookieContent> = {
  en: {
    title: "Cookie Policy",
    body: [
      "This website uses only the cookies strictly necessary for its operation. We do not use advertising or tracking cookies.",
      "By continuing to use this site you agree to the use of essential cookies. You can adjust your browser settings to refuse cookies at any time.",
      "Questions about this policy? Contact us at info@denode.be.",
    ],
  },
  fr: {
    title: "Politique en matière de cookies",
    body: [
      "Ce site web n'utilise que les cookies strictement nécessaires à son fonctionnement. Nous n'utilisons pas de cookies publicitaires ou de suivi.",
      "En continuant à utiliser ce site, vous acceptez l'utilisation des cookies essentiels. Vous pouvez à tout moment configurer votre navigateur pour refuser les cookies.",
      "Des questions sur cette politique ? Contactez-nous à info@denode.be.",
    ],
  },
  nl: {
    title: "Cookiebeleid",
    body: [
      "Deze website gebruikt enkel de cookies die strikt noodzakelijk zijn voor de werking ervan. We gebruiken geen advertentie- of trackingcookies.",
      "Door deze site te blijven gebruiken, ga je akkoord met het gebruik van essentiële cookies. Je kan je browserinstellingen op elk moment aanpassen om cookies te weigeren.",
      "Vragen over dit beleid? Contacteer ons via info@denode.be.",
    ],
  },
};
