import { IMG } from "./content";
import type { Lang } from "./lang";

// ---- Mission / Statutes ---------------------------------------------------
// On the live site the statutes body is English across all languages, so we
// mirror that (single English source rendered on every locale).

export const MISSION_TITLE = "Statutes of the DeNode Foundation";

export const MISSION_SECTIONS: { heading: string; paras: string[] }[] = [
  {
    heading: "Purpose of the foundation (from the statutes)",
    paras: [
      "The private foundation is established for the pursuit of the following disinterested purpose.",
      "The purpose of the private foundation is to acquire, preserve, manage, make accessible, exhibit both publicly and privately, protect, safeguard, and expand art and artworks.",
      "In this context, the private foundation proceeds to inventory, describe, and archive the artworks in the broadest sense.",
      "Furthermore, the private foundation is allowed to improve its collection through sales, purchases, or exchanges with works held by other collectors, artists, or auction houses.",
    ],
  },
  {
    heading: "Supporting activities",
    paras: [
      "To support these activities, the private foundation can oversee the organization or provide support for all artistic achievements and cultural developments, and for organizing art galleries and art exhibitions, both at its own location and elsewhere.",
      "It can publish or distribute promotional material, in print, digitally, or in any other way, or collaborate on or provide support for such.",
    ],
  },
  {
    heading: "Concrete activities",
    paras: [
      "In particular, the private foundation, with a view to realizing this altruistic goal, may carry out the following activities both domestically and internationally:",
      "• The management and expansion of an art collection",
      "• The exhibition of the art collection",
      "• The acquisition of funds and resources necessary for financing the aforementioned purpose",
      "• Financing activities and projects to make the art collection better known to the general public and to inspire young artists",
      "• Facilitating projects with and for artists",
    ],
  },
  {
    heading: "Benefaction",
    paras: [
      "The Board of Directors shall exercise discretionary judgment regarding any potential distributions. Potential beneficiaries shall have no right of claim.",
      "The representation of these interests includes the support and funding of scientific, material, commercial, educational, intellectual, artistic, and other projects, without these individuals having a claim to it and without any distributions being made in cash.",
    ],
  },
  {
    heading: "Use of resources",
    paras: [
      "The private foundation pursues its altruistic goal simultaneously and may use the annual return on the foundation's assets for this purpose.",
      "The private foundation can increase its operating resources by transferring or lending artworks owned by the private foundation for a consideration at a market-conform price, but only to the extent necessary and with a view to preserving the continuity of the operation of the private foundation. The Board decides on this at its discretion with unanimity.",
      "The term 'annual return' shall be understood to mean: the income generated by the assets during that year, increased by realized capital gains on any asset component and unrealized capital gains on capitalization instruments, and decreased by realized capital losses on any asset component and unrealized capital losses on capitalization instruments.",
    ],
  },
  {
    heading: "Liquidation",
    paras: [
      "In the event of liquidation of the private foundation, all movable property, particularly all artworks and the art archive, will be transferred to reputable museums, chosen by the Board, in accordance with the altruistic goal.",
    ],
  },
  {
    heading: "Management of the assets",
    paras: [
      "The private foundation manages its assets like a good householder, with attention to preservation and valorization. It may carry out the following transactions, among others:",
      "• Movable and/or immovable transactions, such as entering into contracts.",
      "• Making investments, directly or indirectly (through the establishment of companies, investment companies, life insurance, etc.).",
      "• Invest in movable property and portfolio values, including securities and works of art.",
      "• Leasing, purchasing and selling, and establishing, constructing, renovating, or demolishing real estate.",
      "• Establish, purchase, or grant business rights, in Belgium or abroad.",
      "• Enter into loans and/or provide securities.",
      "• Assume costs and burdens to relieve the persons or institutions mentioned in the purpose.",
      "• Collaborate with, participate in, or take interests in enterprises of all kinds.",
      "• Transfer assets to other Belgian or foreign foundations or similar legal entities with a corresponding objective.",
      "• Exercise mandates (paid or unpaid) in legal entities.",
    ],
  },
  {
    heading: "Other provisions",
    paras: [
      "The private foundation may furthermore perform all acts that directly or indirectly relate to its purpose. It may provide cooperation and participate in any activity that aligns with its purpose.",
      "The private foundation may not provide any material benefit to the founder(s), directors, or any other person, except if this is part of achieving the altruistic purpose.",
    ],
  },
];

// ---- Team -----------------------------------------------------------------

interface Member {
  name: string;
  role: string;
  bio: string;
  img: string;
}

interface TeamContent {
  aboutHeading: string;
  tagline: string;
  aboutParas: string[];
  teamHeading: string;
  teamSub: string;
  members: Member[];
  volunteersHeading: string;
  volunteersBody: string;
}

export const TEAM: Record<Lang, TeamContent> = {
  en: {
    aboutHeading: "About DeNode Foundation",
    tagline: "A platform for research, creation, and dialogue.",
    aboutParas: [
      "The DeNode Foundation is a non-profit organization based in Ghent dedicated to supporting contemporary art. We believe in artistic practices that look beyond the surface. Therefore, we focus on long-term projects and in-depth research, where the process is at least as important as the end result.",
      "Our foundation is a vibrant ecosystem where exhibitions, residencies, public programs, and editorial projects come together. Instead of limiting ourselves to one medium, we embrace interdisciplinary practices that engage in dialogue with the social, cultural, and philosophical issues of our time. In this way, we bridge the local Ghent scene and the international art field.",
    ],
    teamHeading: "Team",
    teamSub: "The core team of DeNode",
    members: [
      {
        name: "Paul De Cannière",
        role: "Founder & Strategic Vision",
        bio: "Driven by the desire to create a free space for collective reflection, Paul laid the foundation for DeNode. With a keen eye for technological innovation and a strong social commitment, he focuses on projects that transcend conventional formats and aim to generate sustainable impact.",
        img: IMG.paul,
      },
      {
        name: "Kristof Vander Cruyssen",
        role: "Curator & Artistic Development",
        bio: "As an artist and curator, Kristof brings deep insight into artistic ecosystems to the foundation. He oversees the artistic direction and guides the development of exhibitions and residencies. His expertise combines curatorial precision with pragmatic knowledge of production processes.",
        img: IMG.kristof,
      },
      {
        name: "Hanna Ouaziz",
        role: "Curatorial & International Programs",
        bio: "Hanna shapes the substantive narratives and international collaborations of DeNode. With a background in philosophy and anthropology, she weaves thematic research together with engaged art practices. She is the linchpin of our international network and responsible for the editorial projects that deepen our vision.",
        img: IMG.hanna,
      },
    ],
    volunteersHeading: "Volunteers and staff",
    volunteersBody:
      "The realization of our program would be impossible without the tireless dedication of our many staff and volunteers. We see them not just as support, but as co-creators. More information about their individual practices can be found on our Artists page, as they are each the creative engine of our organization.",
  },
  fr: {
    aboutHeading: "À propos de la Fondation DeNode",
    tagline: "Une plateforme pour la recherche, la création et le dialogue.",
    aboutParas: [
      "La DeNode Foundation est une organisation à but non lucratif basée à Gand, dédiée au soutien de l'art contemporain. Nous croyons en des pratiques artistiques qui vont au-delà de la surface. Par conséquent, nous nous concentrons sur des projets à long terme et des recherches approfondies, où le processus est au moins aussi important que le résultat final.",
      "Notre fondation est un écosystème dynamique où les expositions, les résidences, les programmes publics et les projets éditoriaux se rejoignent. Au lieu de nous limiter à un seul médium, nous embrassons des pratiques interdisciplinaires qui dialoguent avec les enjeux sociaux, culturels et philosophiques de notre époque. De cette manière, nous faisons le lien entre la scène locale de Gand et le domaine artistique international.",
    ],
    teamHeading: "Équipe",
    teamSub: "L'équipe principale de DeNode",
    members: [
      {
        name: "Paul De Cannière",
        role: "Fondateur & Vision Stratégique",
        bio: "Animé par le désir de créer un espace libre pour la réflexion collective, Paul a posé les bases de DeNode. Avec un œil attentif à l'innovation technologique et un fort engagement social, il se concentre sur des projets qui transcendent les formats conventionnels et visent à générer un impact durable.",
        img: IMG.paul,
      },
      {
        name: "Kristof Vander Cruyssen",
        role: "Directeur artistique & curateur",
        bio: "En tant que chercheur en art et artiste, Kristof apporte à la fondation une compréhension approfondie des écosystèmes artistiques. Il veille à la direction artistique et accompagne le développement des expositions et des résidences. Son expertise associe une précision curatoriale à une connaissance pragmatique des processus de production.",
        img: IMG.kristof,
      },
      {
        name: "Hanna Ouaziz",
        role: "Programmes de conservation et internationaux",
        bio: "Hanna façonne les récits substantiels et les collaborations internationales de DeNode. Avec un parcours en philosophie et en anthropologie, elle tisse la recherche thématique avec des pratiques artistiques engagées. Elle est le pivot de notre réseau international et responsable des projets éditoriaux qui approfondissent notre vision.",
        img: IMG.hanna,
      },
    ],
    volunteersHeading: "Bénévoles et personnel",
    volunteersBody:
      "La réalisation de notre programme serait impossible sans le dévouement inflexible de notre nombreux personnel et bénévoles. Nous les considérons non seulement comme un soutien, mais comme des co-créateurs. Plus d'informations sur leurs pratiques individuelles peuvent être trouvées sur notre page Artistes, car chacun d'eux est le moteur créatif de notre organisation.",
  },
  nl: {
    aboutHeading: "Over Stichting DeNode",
    tagline: "Een platform voor onderzoek, creatie en dialoog.",
    aboutParas: [
      "Stichting DeNode is een Gentse non-profitorganisatie die zich inzet voor de ondersteuning van hedendaagse kunst. Wij geloven in artistieke praktijken die verder kijken dan het oppervlak. Daarom richten wij ons op langdurige trajecten en diepgaand onderzoek, waarbij het proces minstens even belangrijk is als het eindresultaat.",
      "Onze stichting is een levendig ecosysteem waar tentoonstellingen, residenties, publieke programma's en redactionele projecten samenkomen. In plaats van ons te beperken tot één medium, omarmen we interdisciplinaire praktijken die de dialoog aangaan met sociale, culturele en filosofische vraagstukken van deze tijd. Zo slaan we een brug tussen de lokale Gentse scene en het internationale kunstenveld.",
    ],
    teamHeading: "Team",
    teamSub: "De vaste kern van DeNode",
    members: [
      {
        name: "Paul De Cannière",
        role: "Oprichter & Strategische Visie",
        bio: "Gedreven door de wens om een vrije ruimte te creëren voor collectieve reflectie, legde Paul de basis voor DeNode. Met een scherp oog voor technologische innovatie en een sterke sociale bewogenheid, richt hij zich op projecten die conventionele formats overstijgen en een duurzame impact willen genereren.",
        img: IMG.paul,
      },
      {
        name: "Kristof Vander Cruyssen",
        role: "Artistieke leider & curator",
        bio: "Als kunstwetenschapper en kunstenaar brengt Kristof een diepgaand inzicht in artistieke ecosystemen mee naar de stichting. Hij bewaakt de artistieke koers en begeleidt de ontwikkeling van tentoonstellingen en residenties. Zijn expertise koppelt curatoriële precisie aan een pragmatische kennis van productieprocessen.",
        img: IMG.kristof,
      },
      {
        name: "Hanna Ouaziz",
        role: "Curatoriële & Internationale Programma's",
        bio: "Hanna geeft vorm aan de inhoudelijke narratieven en internationale samenwerkingen van DeNode. Vanuit een achtergrond in de filosofie en antropologie weeft zij thematisch onderzoek samen met geëngageerde kunstpraktijken. Zij is de spil in ons internationale netwerk en verantwoordelijk voor de redactionele projecten die onze visie verdiepen.",
        img: IMG.hanna,
      },
    ],
    volunteersHeading: "Vrijwilligers en medewerkers",
    volunteersBody:
      "De realisatie van ons programma zou onmogelijk zijn zonder de tomeloze inzet van onze vele medewerkers en vrijwilligers. Wij beschouwen hen niet alleen als ondersteuning, maar als mede-makers. Meer informatie over hun individuele praktijken is te vinden op onze Kunstenaars-pagina, want zij zijn stuk voor stuk de creatieve motor van onze organisatie.",
  },
};

// ---- Cookie policy (concise notice — replace with official legal text) -----

interface CookieContent {
  title: string;
  body: string[];
}

export const COOKIE: Record<Lang, CookieContent> = {
  en: {
    title: "Cookie Policy",
    body: [
      "This website uses only the cookies strictly necessary for its operation. We do not use advertising or tracking cookies.",
      "By continuing to use this site you agree to the use of essential cookies. You can adjust your browser settings to refuse cookies at any time.",
      "Questions about this policy? Contact us at info@denode.be.",
    ],
  },
  fr: {
    title: "Politique en matière de cookies",
    body: [
      "Ce site web n'utilise que les cookies strictement nécessaires à son fonctionnement. Nous n'utilisons pas de cookies publicitaires ou de suivi.",
      "En continuant à utiliser ce site, vous acceptez l'utilisation des cookies essentiels. Vous pouvez à tout moment configurer votre navigateur pour refuser les cookies.",
      "Des questions sur cette politique ? Contactez-nous à info@denode.be.",
    ],
  },
  nl: {
    title: "Cookiebeleid",
    body: [
      "Deze website gebruikt enkel de cookies die strikt noodzakelijk zijn voor de werking ervan. We gebruiken geen advertentie- of trackingcookies.",
      "Door deze site te blijven gebruiken, ga je akkoord met het gebruik van essentiële cookies. Je kan je browserinstellingen op elk moment aanpassen om cookies te weigeren.",
      "Vragen over dit beleid? Contacteer ons via info@denode.be.",
    ],
  },
};
